### ISSUE TITLE
Release databraryr 0.5.0

### ISSUE THREAD

**Issue by rogilmore** [databrary/databraryr#55]
First release:

* [x] `usethis::use_news_md()`
* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#sec-code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `git pull`
* [x] Check if any deprecation processes should be advanced, as described in [Gradual deprecation](https://lifecycle.r-lib.org/articles/communicate.html#gradual-deprecation)
* [x] `usethis::use_github_links()`
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [ ] `git push`
* [ ] Draft blog post

Submit to CRAN:

* [x] `usethis::use_version('minor')`
* [x] `devtools::submit_cran()`
* [ ] Approve email

Wait for CRAN...

* [ ] Accepted :tada:
* [ ] Add preemptive link to blog post in pkgdown news menu
* [ ] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version(push = TRUE)`
* [ ] `usethis::use_news_md()`
* [ ] Finish blog post
* [ ] Tweet

**Comment by rogilmore** [comment]
Do we bump version to 0.5.0 or not?

**Comment by JeffSpies** [comment]
I can see arguments in either direction, but bumping the minor to 5 seems reasonable.

**Comment by JeffSpies** [comment]
Everything is looking good here. When do you want to move on to release prep?

**Comment by JeffSpies** [comment]
Will do. I'll register it with your email and let you know when to expect a confirmation.

**Comment by rogilmore** [comment]
Submitted just now. 2023-09-29.
