### ISSUE TITLE
Fix GitHub actions rendering of pkg_down documentation

### ISSUE THREAD

**Issue by rogilmore** [databrary/databraryr#56]

**Comment by JeffSpies** [comment]
We think changing the login_db chunk will fix this issue.

**Comment by rogilmore** [comment]
Added `eval=FALSE` to chunk in the vignette. We'll see soon whether this resolves the pkg_down bug.

**Comment by rogilmore** [comment]
Removing chunk rendering seems to fix.

**Comment by JeffSpies** [comment]
OK, I'll pull and run check to see if there are any other issues remaining.
