### ISSUE TITLE
`devtools::check(remote = TRUE, manual = TRUE)` reveals a set of HTML issues with the documentation files.

### ISSUE THREAD

**Issue by rogilmore** [databrary/databraryr#64]

**Comment by rogilmore** [comment]
Are these critical?

**Comment by JeffSpies** [comment]
Looking at them now.

**Comment by JeffSpies** [comment]
Maybe the docs aren't being tested because of those past errors. If you push the fixes, I'll rerun, but I'm currently not seeing HTML issues.

**Comment by rogilmore** [comment]
Here are the results from `devtools::check(remote = TRUE, manual = TRUE)`:

❯ checking HTML version of manual ... NOTE
  Found the following HTML validation problems:
  GET_db_contents.html:4:1 (GET_db_contents.Rd:5): Warning: <link> inserting "type" attribute
  GET_db_contents.html:12:1 (GET_db_contents.Rd:5): Warning: <script> proprietary attribute "onload"
  GET_db_contents.html:12:1 (GET_db_contents.Rd:5): Warning: <script> inserting "type" attribute
  GET_db_contents.html:17:1 (GET_db_contents.Rd:5): Warning: <table> lacks "summary" attribute
  GET_db_contents.html:40:1 (GET_db_contents.Rd:15): Warning: <table> lacks "summary" attribute
  HHMMSSmmm_to_ms.html:4:1 (HHMMSSmmm_to_ms.Rd:5): Warning: <link> inserting "type" attribute
  HHMMSSmmm_to_ms.html:12:1 (HHMMSSmmm_to_ms.Rd:5): Warning: <script> proprietary attribute "onload"
  HHMMSSmmm_to_ms.html:12:1 (HHMMSSmmm_to_ms.Rd:5): Warning: <script> inserting "type" attribute
  HHMMSSmmm_to_ms.html:17:1 (HHMMSSmmm_to_ms.Rd:5): Warning: <table> lacks "summary" attribute
  HHMMSSmmm_to_ms.html:35:1 (HHMMSSmmm_to_ms.Rd:10): Warning: <table> lacks "summary" attribute
  assign_constants.html:4:1 (assign_constants.Rd:5): Warning: <link> inserting "type" attribute
  assign_constants.html:12:1 (assign_constants.Rd:5): Warning: <script> proprietary attribute "onload"
  assign_constants.html:12:1 (assign_constants.Rd:5): Warning: <script> inserting "type" attribute
  assign_constants.html:17:1 (assign_constants.Rd:5): Warning: <table> lacks "summary" attribute
  assign_constants.html:35:1 (assign_constants.Rd:10): Warning: <table> lacks "summary" attribute
  check_ssl_certs.html:4:1 (check_ssl_certs.Rd:5): Warning: <link> inserting "type" attribute
  check_ssl_certs.html:12:1 (check_ssl_certs.Rd:5): Warning: <script> proprietary attribute "onload"
  check_ssl_certs.html:12:1 (check_ssl_certs.Rd:5): Warning: <script> inserting "type" attribute
  check_ssl_certs.html:17:1 (check_ssl_certs.Rd:5): Warning: <table> lacks "summary" attribute
  check_ssl_certs.html:35:1 (check_ssl_certs.Rd:10): Warning: <table> lacks "summary" attribute
  databraryr-package.html:4:1 (databraryr-package.Rd:7): Warning: <link> inserting "type" attribute
  databraryr-package.html:12:1 (databraryr-package.Rd:7): Warning: <script> proprietary attribute "onload"
  databraryr-package.html:12:1 (databraryr-package.Rd:7): Warning: <script> inserting "type" attribute
  databraryr-package.html:17:1 (databraryr-package.Rd:7): Warning: <table> lacks "summary" attribute
  download_asset.html:4:1 (download_asset.Rd:5): Warning: <link> inserting "type" attribute
  download_asset.html:12:1 (download_asset.Rd:5): Warning: <script> proprietary attribute "onload"
  download_asset.html:12:1 (download_asset.Rd:5): Warning: <script> inserting "type" attribute
  download_asset.html:17:1 (download_asset.Rd:5): Warning: <table> lacks "summary" attribute
  download_asset.html:42:1 (download_asset.Rd:17): Warning: <table> lacks "summary" attribute
  download_party.html:4:1 (download_party.Rd:5): Warning: <link> inserting "type" attribute
  download_party.html:12:1 (download_party.Rd:5): Warning: <script> proprietary attribute "onload"
  download_party.html:12:1 (download_party.Rd:5): Warning: <script> inserting "type" attribute
  download_party.html:17:1 (download_party.Rd:5): Warning: <table> lacks "summary" attribute
  download_party.html:37:1 (download_party.Rd:10): Warning: <table> lacks "summary" attribute
  download_party_avatar.html:4:1 (download_party_avatar.Rd:5): Warning: <link> inserting "type" attribute
  download_party_avatar.html:12:1 (download_party_avatar.Rd:5): Warning: <script> proprietary attribute "onload"
  download_party_avatar.html:12:1 (download_party_avatar.Rd:5): Warning: <script> inserting "type" attribute
  download_party_avatar.html:17:1 (download_party_avatar.Rd:5): Warning: <table> lacks "summary" attribute
  download_party_avatar.html:35:1 (download_party_avatar.Rd:10): Warning: <table> lacks "summary" attribute
  download_session_csv.html:4:1 (download_session_csv.Rd:5): Warning: <link> inserting "type" attribute
  download_session_csv.html:12:1 (download_session_csv.Rd:5): Warning: <script> proprietary attribute "onload"
  download_session_csv.html:12:1 (download_session_csv.Rd:5): Warning: <script> inserting "type" attribute
  download_session_csv.html:17:1 (download_session_csv.Rd:5): Warning: <table> lacks "summary" attribute
  download_session_csv.html:41:1 (download_session_csv.Rd:16): Warning: <table> lacks "summary" attribute
  get_asset_segment_range.html:4:1 (get_asset_segment_range.Rd:5): Warning: <link> inserting "type" attribute
  get_asset_segment_range.html:12:1 (get_asset_segment_range.Rd:5): Warning: <script> proprietary attribute "onload"
  get_asset_segment_range.html:12:1 (get_asset_segment_range.Rd:5): Warning: <script> inserting "type" attribute
  get_asset_segment_range.html:17:1 (get_asset_segment_range.Rd:5): Warning: <table> lacks "summary" attribute
  get_asset_segment_range.html:42:1 (get_asset_segment_range.Rd:17): Warning: <table> lacks "summary" attribute
  get_db_stats.html:4:1 (get_db_stats.Rd:5): Warning: <link> inserting "type" attribute
  get_db_stats.html:12:1 (get_db_stats.Rd:5): Warning: <script> proprietary attribute "onload"
  get_db_stats.html:12:1 (get_db_stats.Rd:5): Warning: <script> inserting "type" attribute
  get_db_stats.html:17:1 (get_db_stats.Rd:5): Warning: <table> lacks "summary" attribute
  get_db_stats.html:35:1 (get_db_stats.Rd:10): Warning: <table> lacks "summary" attribute
  get_file_duration.html:4:1 (get_file_duration.Rd:5): Warning: <link> inserting "type" attribute
  get_file_duration.html:12:1 (get_file_duration.Rd:5): Warning: <script> proprietary attribute "onload"
  get_file_duration.html:12:1 (get_file_duration.Rd:5): Warning: <script> inserting "type" attribute
  get_file_duration.html:17:1 (get_file_duration.Rd:5): Warning: <table> lacks "summary" attribute
  get_file_duration.html:39:1 (get_file_duration.Rd:14): Warning: <table> lacks "summary" attribute
  get_party_as_df.html:4:1 (get_party_as_df.Rd:5): Warning: <link> inserting "type" attribute
  get_party_as_df.html:12:1 (get_party_as_df.Rd:5): Warning: <script> proprietary attribute "onload"
  get_party_as_df.html:12:1 (get_party_as_df.Rd:5): Warning: <script> inserting "type" attribute
  get_party_as_df.html:17:1 (get_party_as_df.Rd:5): Warning: <table> lacks "summary" attribute
  get_party_as_df.html:35:1 (get_party_as_df.Rd:10): Warning: <table> lacks "summary" attribute
  get_permission_levels.html:4:1 (get_permission_levels.Rd:5): Warning: <link> inserting "type" attribute
  get_permission_levels.html:12:1 (get_permission_levels.Rd:5): Warning: <script> proprietary attribute "onload"
  get_permission_levels.html:12:1 (get_permission_levels.Rd:5): Warning: <script> inserting "type" attribute
  get_permission_levels.html:17:1 (get_permission_levels.Rd:5): Warning: <table> lacks "summary" attribute
  get_permission_levels.html:35:1 (get_permission_levels.Rd:10): Warning: <table> lacks "summary" attribute
  get_release_levels.html:4:1 (get_release_levels.Rd:5): Warning: <link> inserting "type" attribute
  get_release_levels.html:12:1 (get_release_levels.Rd:5): Warning: <script> proprietary attribute "onload"
  get_release_levels.html:12:1 (get_release_levels.Rd:5): Warning: <script> inserting "type" attribute
  get_release_levels.html:17:1 (get_release_levels.Rd:5): Warning: <table> lacks "summary" attribute
  get_release_levels.html:35:1 (get_release_levels.Rd:10): Warning: <table> lacks "summary" attribute
  get_session_as_df.html:4:1 (get_session_as_df.Rd:5): Warning: <link> inserting "type" attribute
  get_session_as_df.html:12:1 (get_session_as_df.Rd:5): Warning: <script> proprietary attribute "onload"
  get_session_as_df.html:12:1 (get_session_as_df.Rd:5): Warning: <script> inserting "type" attribute
  get_session_as_df.html:17:1 (get_session_as_df.Rd:5): Warning: <table> lacks "summary" attribute
  get_session_as_df.html:35:1 (get_session_as_df.Rd:10): Warning: <table> lacks "summary" attribute
  get_supported_file_types.html:4:1 (get_supported_file_types.Rd:5): Warning: <link> inserting "type" attribute
  get_supported_file_types.html:12:1 (get_supported_file_types.Rd:5): Warning: <script> proprietary attribute "onload"
  get_supported_file_types.html:12:1 (get_supported_file_types.Rd:5): Warning: <script> inserting "type" attribute
  get_supported_file_types.html:17:1 (get_supported_file_types.Rd:5): Warning: <table> lacks "summary" attribute
  get_supported_file_types.html:35:1 (get_supported_file_types.Rd:10): Warning: <table> lacks "summary" attribute
  get_video_stats.html:4:1 (get_video_stats.Rd:5): Warning: <link> inserting "type" attribute
  get_video_stats.html:12:1 (get_video_stats.Rd:5): Warning: <script> proprietary attribute "onload"
  get_video_stats.html:12:1 (get_video_stats.Rd:5): Warning: <script> inserting "type" attribute
  get_video_stats.html:17:1 (get_video_stats.Rd:5): Warning: <table> lacks "summary" attribute
  get_video_stats.html:35:1 (get_video_stats.Rd:10): Warning: <table> lacks "summary" attribute
  is_institution.html:4:1 (is_institution.Rd:5): Warning: <link> inserting "type" attribute
  is_institution.html:12:1 (is_institution.Rd:5): Warning: <script> proprietary attribute "onload"
  is_institution.html:12:1 (is_institution.Rd:5): Warning: <script> inserting "type" attribute
  is_institution.html:17:1 (is_institution.Rd:5): Warning: <table> lacks "summary" attribute
  is_institution.html:35:1 (is_institution.Rd:10): Warning: <table> lacks "summary" attribute
  is_person.html:4:1 (is_person.Rd:5): Warning: <link> inserting "type" attribute
  is_person.html:12:1 (is_person.Rd:5): Warning: <script> proprietary attribute "onload"
  is_person.html:12:1 (is_person.Rd:5): Warning: <script> inserting "type" attribute
  is_person.html:17:1 (is_person.Rd:5): Warning: <table> lacks "summary" attribute
  is_person.html:35:1 (is_person.Rd:10): Warning: <table> lacks "summary" attribute
  list_affiliates.html:4:1 (list_affiliates.Rd:5): Warning: <link> inserting "type" attribute
  list_affiliates.html:12:1 (list_affiliates.Rd:5): Warning: <script> proprietary attribute "onload"
  list_affiliates.html:12:1 (list_affiliates.Rd:5): Warning: <script> inserting "type" attribute
  list_affiliates.html:17:1 (list_affiliates.Rd:5): Warning: <table> lacks "summary" attribute
  list_affiliates.html:35:1 (list_affiliates.Rd:10): Warning: <table> lacks "summary" attribute
  list_assets_by_type.html:4:1 (list_assets_by_type.Rd:5): Warning: <link> inserting "type" attribute
  list_assets_by_type.html:12:1 (list_assets_by_type.Rd:5): Warning: <script> proprietary attribute "onload"
  list_assets_by_type.html:12:1 (list_assets_by_type.Rd:5): Warning: <script> inserting "type" attribute
  list_assets_by_type.html:17:1 (list_assets_by_type.Rd:5): Warning: <table> lacks "summary" attribute
  list_assets_by_type.html:35:1 (list_assets_by_type.Rd:10): Warning: <table> lacks "summary" attribute
  list_assets_in_session.html:4:1 (list_assets_in_session.Rd:5): Warning: <link> inserting "type" attribute
  list_assets_in_session.html:12:1 (list_assets_in_session.Rd:5): Warning: <script> proprietary attribute "onload"
  list_assets_in_session.html:12:1 (list_assets_in_session.Rd:5): Warning: <script> inserting "type" attribute
  list_assets_in_session.html:17:1 (list_assets_in_session.Rd:5): Warning: <table> lacks "summary" attribute
  list_assets_in_session.html:35:1 (list_assets_in_session.Rd:10): Warning: <table> lacks "summary" attribute
  list_assets_in_volume.html:4:1 (list_assets_in_volume.Rd:5): Warning: <link> inserting "type" attribute
  list_assets_in_volume.html:12:1 (list_assets_in_volume.Rd:5): Warning: <script> proprietary attribute "onload"
  list_assets_in_volume.html:12:1 (list_assets_in_volume.Rd:5): Warning: <script> inserting "type" attribute
  list_assets_in_volume.html:17:1 (list_assets_in_volume.Rd:5): Warning: <table> lacks "summary" attribute
  list_assets_in_volume.html:35:1 (list_assets_in_volume.Rd:10): Warning: <table> lacks "summary" attribute
  list_containers_records.html:4:1 (list_containers_records.Rd:5): Warning: <link> inserting "type" attribute
  list_containers_records.html:12:1 (list_containers_records.Rd:5): Warning: <script> proprietary attribute "onload"
  list_containers_records.html:12:1 (list_containers_records.Rd:5): Warning: <script> inserting "type" attribute
  list_containers_records.html:17:1 (list_containers_records.Rd:5): Warning: <table> lacks "summary" attribute
  list_containers_records.html:35:1 (list_containers_records.Rd:10): Warning: <table> lacks "summary" attribute
  list_individual_sponsors.html:4:1 (list_individual_sponsors.Rd:5): Warning: <link> inserting "type" attribute
  list_individual_sponsors.html:12:1 (list_individual_sponsors.Rd:5): Warning: <script> proprietary attribute "onload"
  list_individual_sponsors.html:12:1 (list_individual_sponsors.Rd:5): Warning: <script> inserting "type" attribute
  list_individual_sponsors.html:17:1 (list_individual_sponsors.Rd:5): Warning: <table> lacks "summary" attribute
  list_individual_sponsors.html:41:1 (list_individual_sponsors.Rd:14): Warning: <table> lacks "summary" attribute
  list_institutional_sponsors.html:4:1 (list_institutional_sponsors.Rd:5): Warning: <link> inserting "type" attribute
  list_institutional_sponsors.html:12:1 (list_institutional_sponsors.Rd:5): Warning: <script> proprietary attribute "onload"
  list_institutional_sponsors.html:12:1 (list_institutional_sponsors.Rd:5): Warning: <script> inserting "type" attribute
  list_institutional_sponsors.html:17:1 (list_institutional_sponsors.Rd:5): Warning: <table> lacks "summary" attribute
  list_institutional_sponsors.html:41:1 (list_institutional_sponsors.Rd:14): Warning: <table> lacks "summary" attribute
  list_party.html:4:1 (list_party.Rd:5): Warning: <link> inserting "type" attribute
  list_party.html:12:1 (list_party.Rd:5): Warning: <script> proprietary attribute "onload"
  list_party.html:12:1 (list_party.Rd:5): Warning: <script> inserting "type" attribute
  list_party.html:17:1 (list_party.Rd:5): Warning: <table> lacks "summary" attribute
  list_party.html:35:1 (list_party.Rd:10): Warning: <table> lacks "summary" attribute
  list_people.html:4:1 (list_people.Rd:5): Warning: <link> inserting "type" attribute
  list_people.html:12:1 (list_people.Rd:5): Warning: <script> proprietary attribute "onload"
  list_people.html:12:1 (list_people.Rd:5): Warning: <script> inserting "type" attribute
  list_people.html:17:1 (list_people.Rd:5): Warning: <table> lacks "summary" attribute
  list_people.html:35:1 (list_people.Rd:10): Warning: <table> lacks "summary" attribute
  list_session_activity.html:4:1 (list_session_activity.Rd:5): Warning: <link> inserting "type" attribute
  list_session_activity.html:12:1 (list_session_activity.Rd:5): Warning: <script> proprietary attribute "onload"
  list_session_activity.html:12:1 (list_session_activity.Rd:5): Warning: <script> inserting "type" attribute
  list_session_activity.html:17:1 (list_session_activity.Rd:5): Warning: <table> lacks "summary" attribute
  list_session_activity.html:36:1 (list_session_activity.Rd:10): Warning: <table> lacks "summary" attribute
  list_sessions.html:4:1 (list_sessions.Rd:5): Warning: <link> inserting "type" attribute
  list_sessions.html:12:1 (list_sessions.Rd:5): Warning: <script> proprietary attribute "onload"
  list_sessions.html:12:1 (list_sessions.Rd:5): Warning: <script> inserting "type" attribute
  list_sessions.html:17:1 (list_sessions.Rd:5): Warning: <table> lacks "summary" attribute
  list_sessions.html:35:1 (list_sessions.Rd:10): Warning: <table> lacks "summary" attribute
  list_sessions_in_volume.html:4:1 (list_sessions_in_volume.Rd:5): Warning: <link> inserting "type" attribute
  list_sessions_in_volume.html:12:1 (list_sessions_in_volume.Rd:5): Warning: <script> proprietary attribute "onload"
  list_sessions_in_volume.html:12:1 (list_sessions_in_volume.Rd:5): Warning: <script> inserting "type" attribute
  list_sessions_in_volume.html:17:1 (list_sessions_in_volume.Rd:5): Warning: <table> lacks "summary" attribute
  list_sessions_in_volume.html:36:1 (list_sessions_in_volume.Rd:10): Warning: <table> lacks "summary" attribute
  list_specified_assets_in_session.html:4:1 (list_specified_assets_in_session.Rd:5): Warning: <link> inserting "type" attribute
  list_specified_assets_in_session.html:12:1 (list_specified_assets_in_session.Rd:5): Warning: <script> proprietary attribute "onload"
  list_specified_assets_in_session.html:12:1 (list_specified_assets_in_session.Rd:5): Warning: <script> inserting "type" attribute
  list_specified_assets_in_session.html:17:1 (list_specified_assets_in_session.Rd:5): Warning: <table> lacks "summary" attribute
  list_specified_assets_in_session.html:39:1 (list_specified_assets_in_session.Rd:14): Warning: <table> lacks "summary" attribute
  list_sponsors.html:4:1 (list_sponsors.Rd:5): Warning: <link> inserting "type" attribute
  list_sponsors.html:12:1 (list_sponsors.Rd:5): Warning: <script> proprietary attribute "onload"
  list_sponsors.html:12:1 (list_sponsors.Rd:5): Warning: <script> inserting "type" attribute
  list_sponsors.html:17:1 (list_sponsors.Rd:5): Warning: <table> lacks "summary" attribute
  list_sponsors.html:35:1 (list_sponsors.Rd:10): Warning: <table> lacks "summary" attribute
  list_volume.html:4:1 (list_volume.Rd:5): Warning: <link> inserting "type" attribute
  list_volume.html:12:1 (list_volume.Rd:5): Warning: <script> proprietary attribute "onload"
  list_volume.html:12:1 (list_volume.Rd:5): Warning: <script> inserting "type" attribute
  list_volume.html:17:1 (list_volume.Rd:5): Warning: <table> lacks "summary" attribute
  list_volume.html:35:1 (list_volume.Rd:10): Warning: <table> lacks "summary" attribute
  list_volume_activity.html:4:1 (list_volume_activity.Rd:5): Warning: <link> inserting "type" attribute
  list_volume_activity.html:12:1 (list_volume_activity.Rd:5): Warning: <script> proprietary attribute "onload"
  list_volume_activity.html:12:1 (list_volume_activity.Rd:5): Warning: <script> inserting "type" attribute
  list_volume_activity.html:17:1 (list_volume_activity.Rd:5): Warning: <table> lacks "summary" attribute
  list_volume_activity.html:36:1 (list_volume_activity.Rd:10): Warning: <table> lacks "summary" attribute
  list_volume_excerpts.html:4:1 (list_volume_excerpts.Rd:5): Warning: <link> inserting "type" attribute
  list_volume_excerpts.html:12:1 (list_volume_excerpts.Rd:5): Warning: <script> proprietary attribute "onload"
  list_volume_excerpts.html:12:1 (list_volume_excerpts.Rd:5): Warning: <script> inserting "type" attribute
  list_volume_excerpts.html:17:1 (list_volume_excerpts.Rd:5): Warning: <table> lacks "summary" attribute
  list_volume_excerpts.html:35:1 (list_volume_excerpts.Rd:10): Warning: <table> lacks "summary" attribute
  list_volume_funding.html:4:1 (list_volume_funding.Rd:5): Warning: <link> inserting "type" attribute
  list_volume_funding.html:12:1 (list_volume_funding.Rd:5): Warning: <script> proprietary attribute "onload"
  list_volume_funding.html:12:1 (list_volume_funding.Rd:5): Warning: <script> inserting "type" attribute
  list_volume_funding.html:17:1 (list_volume_funding.Rd:5): Warning: <table> lacks "summary" attribute
  list_volume_funding.html:35:1 (list_volume_funding.Rd:10): Warning: <table> lacks "summary" attribute
  list_volume_links.html:4:1 (list_volume_links.Rd:5): Warning: <link> inserting "type" attribute
  list_volume_links.html:12:1 (list_volume_links.Rd:5): Warning: <script> proprietary attribute "onload"
  list_volume_links.html:12:1 (list_volume_links.Rd:5): Warning: <script> inserting "type" attribute
  list_volume_links.html:17:1 (list_volume_links.Rd:5): Warning: <table> lacks "summary" attribute
  list_volume_links.html:35:1 (list_volume_links.Rd:10): Warning: <table> lacks "summary" attribute
  list_volume_metadata.html:4:1 (list_volume_metadata.Rd:5): Warning: <link> inserting "type" attribute
  list_volume_metadata.html:12:1 (list_volume_metadata.Rd:5): Warning: <script> proprietary attribute "onload"
  list_volume_metadata.html:12:1 (list_volume_metadata.Rd:5): Warning: <script> inserting "type" attribute
  list_volume_metadata.html:17:1 (list_volume_metadata.Rd:5): Warning: <table> lacks "summary" attribute
  list_volume_metadata.html:40:1 (list_volume_metadata.Rd:15): Warning: <table> lacks "summary" attribute
  list_volume_owners.html:4:1 (list_volume_owners.Rd:5): Warning: <link> inserting "type" attribute
  list_volume_owners.html:12:1 (list_volume_owners.Rd:5): Warning: <script> proprietary attribute "onload"
  list_volume_owners.html:12:1 (list_volume_owners.Rd:5): Warning: <script> inserting "type" attribute
  list_volume_owners.html:17:1 (list_volume_owners.Rd:5): Warning: <table> lacks "summary" attribute
  list_volume_owners.html:35:1 (list_volume_owners.Rd:10): Warning: <table> lacks "summary" attribute
  list_volume_tags.html:4:1 (list_volume_tags.Rd:5): Warning: <link> inserting "type" attribute
  list_volume_tags.html:12:1 (list_volume_tags.Rd:5): Warning: <script> proprietary attribute "onload"
  list_volume_tags.html:12:1 (list_volume_tags.Rd:5): Warning: <script> inserting "type" attribute
  list_volume_tags.html:17:1 (list_volume_tags.Rd:5): Warning: <table> lacks "summary" attribute
  list_volume_tags.html:35:1 (list_volume_tags.Rd:10): Warning: <table> lacks "summary" attribute
  login_db.html:4:1 (login_db.Rd:5): Warning: <link> inserting "type" attribute
  login_db.html:12:1 (login_db.Rd:5): Warning: <script> proprietary attribute "onload"
  login_db.html:12:1 (login_db.Rd:5): Warning: <script> inserting "type" attribute
  login_db.html:17:1 (login_db.Rd:5): Warning: <table> lacks "summary" attribute
  login_db.html:42:1 (login_db.Rd:17): Warning: <table> lacks "summary" attribute
  logout_db.html:4:1 (logout_db.Rd:5): Warning: <link> inserting "type" attribute
  logout_db.html:12:1 (logout_db.Rd:5): Warning: <script> proprietary attribute "onload"
  logout_db.html:12:1 (logout_db.Rd:5): Warning: <script> inserting "type" attribute
  logout_db.html:17:1 (logout_db.Rd:5): Warning: <table> lacks "summary" attribute
  logout_db.html:35:1 (logout_db.Rd:10): Warning: <table> lacks "summary" attribute
  read_csv_data_as_df.html:4:1 (read_csv_data_as_df.Rd:5): Warning: <link> inserting "type" attribute
  read_csv_data_as_df.html:12:1 (read_csv_data_as_df.Rd:5): Warning: <script> proprietary attribute "onload"
  read_csv_data_as_df.html:12:1 (read_csv_data_as_df.Rd:5): Warning: <script> inserting "type" attribute
  read_csv_data_as_df.html:17:1 (read_csv_data_as_df.Rd:5): Warning: <table> lacks "summary" attribute
  read_csv_data_as_df.html:36:1 (read_csv_data_as_df.Rd:10): Warning: <table> lacks "summary" attribute
  search_for_funder.html:4:1 (search_for_funder.Rd:5): Warning: <link> inserting "type" attribute
  search_for_funder.html:12:1 (search_for_funder.Rd:5): Warning: <script> proprietary attribute "onload"
  search_for_funder.html:12:1 (search_for_funder.Rd:5): Warning: <script> inserting "type" attribute
  search_for_funder.html:17:1 (search_for_funder.Rd:5): Warning: <table> lacks "summary" attribute
  search_for_funder.html:35:1 (search_for_funder.Rd:10): Warning: <table> lacks "summary" attribute
  search_for_keywords.html:4:1 (search_for_keywords.Rd:5): Warning: <link> inserting "type" attribute
  search_for_keywords.html:12:1 (search_for_keywords.Rd:5): Warning: <script> proprietary attribute "onload"
  search_for_keywords.html:12:1 (search_for_keywords.Rd:5): Warning: <script> inserting "type" attribute
  search_for_keywords.html:17:1 (search_for_keywords.Rd:5): Warning: <table> lacks "summary" attribute
  search_for_keywords.html:35:1 (search_for_keywords.Rd:10): Warning: <table> lacks "summary" attribute
  search_for_tags.html:4:1 (search_for_tags.Rd:5): Warning: <link> inserting "type" attribute
  search_for_tags.html:12:1 (search_for_tags.Rd:5): Warning: <script> proprietary attribute "onload"
  search_for_tags.html:12:1 (search_for_tags.Rd:5): Warning: <script> inserting "type" attribute
  search_for_tags.html:17:1 (search_for_tags.Rd:5): Warning: <table> lacks "summary" attribute
  search_for_tags.html:35:1 (search_for_tags.Rd:10): Warning: <table> lacks "summary" attribute

**Comment by JeffSpies** [comment]
Just pulled and reran. No warnings or errors. Two notes:

```
N  checking CRAN incoming feasibility (17.1s)
...
   Found the following (possibly) invalid URLs:
     URL: https://databrary.github.io/databraryr (moved to https://databrary.github.io/databraryr/)
       From: README.md
       Status: 200
       Message: OK
```

and

```
N  checking package dependencies (3s)
   Package suggested but not available for checking: 'av'
```

**Comment by rogilmore** [comment]
Decided to ignore
